---
output:
  html_document: default
---
# 2017-09-20 {-}

# [Capacity cuts fuel a commodity rally and a debate](https://www.economist.com/news/finance-and-economics/21728623-one-biggest-and-more-controversial-trends-global-economy-capacity)  

從毛澤東提出『大躍進運動』以來，鋼鐵及煤炭業是早期帶動中國經濟發展的火車頭，而如今因產量過剩讓價格始終低迷，中國政府為了讓供需平衡及抬動價格，關閉了許多生產動能及工廠，造成許多工人『下崗』（失業）。

由於中國的重工業還是由國營事業獨佔或寡占，讓中央政府易於操縱產量和價格。過去歐美國家的重工業公司紛紛指責中國過量生產的便宜鋼鐵充斥整個市場，現在卻受惠於中國減少產量的政策。

# [Why Macau is less demanding of democracy than Hong Kong](https://www.economist.com/blogs/economist-explains/2017/09/economist-explains-11)

香港與澳門擁有近似的歷史與沿革，都是中國的特別行政區，但究竟是什麼因素導致香港對民主懷有極高的意識與渴望，而澳門在這塊卻不如香港積極呢?

首先，澳門是中國唯一合法的賭區，這為澳門帶來驚人的收入，每年人均所得為$73,187美金，高出香港68%，而其中大多數都由政府支持。再者，文革期間，共產思想便已經在澳門醞釀，而香港則對共產主義進行取締，之中的差異使得兩地的民眾對中國政權的接受度普遍不同。

然而，與中國接軌後也引發許多社會現象，使澳門人怨聲載道，例如：房價飆高、社會住宅不足。這些都跟香港有異曲同工之妙。

兩者對中國政權的態度最直接反映在選舉上，在澳門，支持更一步民主化的政黨僅獲得少數的選票與席次，而在香港，立場傾向民主化的候選人則占了半數以上的席次。

# [What machines can tell from your face](https://www.economist.com/news/leaders/21728617-life-age-facial-recognition-what-machines-can-tell-your-face)

科技正迅速趕上人類識別臉孔的能力，常見的應用方面包括確認出席情況、逮捕犯人、或是手機解鎖等等...與其他人類偉大發明而言，看似只是錦上添花，但有一天將會使人類的隱私、公平和信任等觀念發生根本性的改變。

從隱私來看，相比指紋等生物特徵最大的區別，人臉可以遠距離起作用，代表人們只要有手機就可以拍下照片，供人臉識別程序使用。雖然我們常用的facebook面部圖片庫不能被其他人提取，但是，像是一些私人企業，可以透過獲得汽車展到訪者的照片，用人臉識別技術在自己的網站上找到這些人，向他們發送汽車廣告。即使私人公司無法將身分和照片聯繫起來，國家往往可以做到。中國政府有公民面部紀錄；美國半數成年人的照片儲存在數據庫中，可供FBI使用。雖然做為追蹤嫌犯是強大的武器，但也可能讓公民隱私造成巨大損害。

在醫療方面，我們可以藉由臉部特徵分析一些罕見疾病，並且和其他手段相比，就早早發現了病情。但這個技術也造成威脅，史丹福大學的研究人員證明，面對一個同性戀者和異性戀者的照片，識別率可以達81％，在視同性戀為犯罪的國家，這個技術令人恐懼。

最後，此技術可能影響社交互動的本質，想像人類的喜怒哀樂，可以透過計算機數據測量，婚姻和工作關係都會變得更真實，但是更不和諧。雖然在民主國家，立法可以改變利與弊之間的平衡。但這類規定不能改變發展的方向，從化妝到配戴太陽眼鏡，試圖欺騙人臉識別系統的努力都以挫敗。Google明確表示不會面部訊息和身分匹配，擔心被非民主政權濫用。其他的科技公司似乎沒這麼講究，政府也不會放棄自己的利益，改變即將到來，直視他吧!

# [Governments need to rethink their attitudes to debt](https://www.economist.com/news/finance-and-economics/21728628-fight-next-recession-fiscal-stimulus-may-matter-more-monetary)

當一國面臨經濟衰退，央行具有較敏銳的嗅覺，因此貨幣政策通常先行於財政政策。隨低利時代的來臨，利率調降的下限是零，否則人們接著便會放棄以金融機構作為存放現金的方式，調降利率的寬鬆政策將開始受到侷限，效果也將不如以往。

若貨幣政策無法有效刺激景氣，則政府的財政政策便扮演重要角色。1970及1980年代的經驗看來，以舉債作為財源的財政政策往往使物價的漲幅甚於經濟的成長，經濟學家也提出看法，指出這樣的刺激景氣的作法其「乘數效果」非常小，他們認為人們會減少消費以因應未來稅的增加，如此兩者便相互抵消了。但是，自2008金融海嘯過後，研究發現財政政策的刺激確實發揮作用，乘數效果甚至接近二，尤其是在貨幣政策受到限制的情況下效果更明顯。

對於「舉債」這項財政預算來源，其融資成本將受到該國的還款能力決定，當還款能力越差，面對的利率便越高。2009年底，希臘公債利率開始攀升，隨後歐元區國家的公債利率也於2010至2012年間隨之上揚，最終引發歐債危機。歐債危機如今已消逝，但事實上，今日多數歐洲國家的債務水準甚至高於2012年歐債危機時，但是利率不升反降的原因在於:似乎各國都認為歐洲央行對那些出問題的國家伸出援手購買其公債，一方面為了解決歐元生存的問題，另一方面為了緩解通貨緊縮，中央銀行的資產購買似乎逐漸變成一種習以為常的行為。

當經濟體落入流動性陷阱，財政政策較有利於經濟體的復甦與成長，近日也有論文指出，一項大力的財政刺激並不會產生較高的債務占GDP比(債務/GDP X 100%)或較高的借款成本，歸因於通常這種大規模財政政策安撫了市場對於信用的擔憂。另一項對於財政政策的建議則是增加其機動性，使財政政策也能夠自動隨著景氣的變化做出反應，例如將勞工的稅率與失業率做連結、預先做好準備的基礎建設計畫等。如此一來，經濟體面臨衰退時便能做出及時的反應。

貨幣政策雖然成功地壓低利率，安定全球經濟體的動盪，但似乎各國最根本的經濟問題仍未解決，而財政政策可以是一個國家的經濟指導方針，能夠改變一國的產業結構、所得分配，或許是未來各國政府擺脫經濟停滯的一條出路。

# [How to manage the computer-security threat](https://www.economist.com/news/leaders/21720279-incentives-software-firms-take-security-seriously-are-too-weak-how-manage)  

過去人們不夠重視網路安全，但近年來由於網路愈來愈發達，已與我們的生活密不可分，網路安全顯得愈發重要。

現今已發展出一些提升網路安全的方法：一.政府政策。由於網路使用者可能會因為缺乏專業知識導致無法保護自己，政府可制定一些政策從旁協助；二.法律責任。基於過去許多企業會拒絕承認自己的網路安全出問題，因此將法律責任歸屬明確可防止企業隱藏內部的網路漏洞；三.保險。可以減輕企業進行網路安全政策的負擔，增加企業提升網路安全的誘因。

為了避免錯誤不斷上演，是時候該改變態度，重視網路安全了，這不僅需要技術，也需要經濟工具的使用。

# [Buttonwood--Why are investors so relaxed about the tensions in Korea?](https://www.economist.com/news/finance-and-economics/21728625-markets-have-concluded-kim-jong-un-and-donald-trump-are-blusterers-why-are)

當北韓試射飛彈挑動國際敏感神經，川普表示對此將不惜一戰的同時，國際的投資行為似乎诶有太大的改變。金價僅微升，美國十年期公債殖利率比8月還低，連應該對此最敏感的南韓股市表現也比年初來的好。

對於這樣現象的解釋有兩個，第一個可能是市場對於政治的風險評估反應不佳，就像是沒有預期看到英國脫歐和川普當選。另一個是投資人已經能適應並學習到這些衝擊只會是短期的，經濟成長和合作的利益會大過這些短期的損害，而有些使用演算法的投資人，政治因素在計算的過程中佔的比例並不高。

若戰爭發生不僅是對南北韓造成影響，附近的中國與日本都會備受牽連。目前40%的液晶顯示器、17%的半導體都在南韓生產，這所相關產業造成的損害將會非常巨大。這些經濟上的限制讓投資人認為美國與北韓間的武力威嚇只是說說而已。
