---
output:
  html_document: default
---
# 2017-10-11 {-}

# [Venture capitalists with daughters are more successful](https://www.economist.com/news/finance-and-economics/21729801-daughters-have-effect-hiring-policies-which-leads-greater-success-venture)
 加拿大帝國商業銀行前總裁 RICHARD NESBITT一直是婦女在商業領域的傳道者。
 
 參閱他與Barbara Annis 合著的《Results at the Top》，他努力呼籲男性正視婦女力量的崛起，並強調數據顯示:「擁有越多女性高階經理人的公司越成功」。
另外他也提出另一項有趣的觀察:「育有女兒的男性員工更容易理解他的訊息」。至少對於風險投資公司來說，近期的研究都證實這項觀察，也再次強化了「性別的多樣性有助於提高公司績效」的主張。

 哈佛大學的Paul Gompers與Sophie Wang試圖證實:是否風險投資公司雇用越多女性經理人，真的能有效提高績效? 然而回答這個問題十分棘手，原因是僱用更多女性的公司可能同時擁有其他導致成功的特徵。風險投資仍然是男性主導的活動，在作者於301間企業、共988檔風險投資基金的樣本中，只有約8％的新員工是女性，而且很少有公司聘請超過一名女性經理人。聘請更多女性的管理合夥人可能會因為公約而隱藏起來 ─ 因為這對新創技術的投資人來說更有吸引力。

作者需要另一種新方法來獨立衡量女性成功的因素。理想情況下，一個隨機的變數都會影響一間公司雇用女性的數量，而作者看中的是「所撫養的女兒數量」這個因素。

親子關係足以改變觀點。當風險投資公司合夥人擁有多一名女兒而非兒子時，平均來說多雇用了2%的女性經理，這也使得公司雇用一名女資深經理的機率高出24%。

研究人員推斷: 擁有女兒及成功之間的關聯，可歸因於更高比例的女性經理人。合夥人育有一額外的女兒而非兒子，其交易成功率可能會高出2.9％ (定義為公司受到首次公開發行、或其他獲利機會的支持)，而這些公司也擁有較高的內部回報率。雇用女性的確是個健全的商業策略。

Nesbitt 指出這一發現符合他的著作之一：「商業中的性別多樣性增加了思想的多元性，已達成更好的決策」。然而此研究報告本身即不太可能促使更多女性進入辦公室，為了達成目標，男性不僅理性上必須接受女性的影響力、更應起身捍衛之。

# [How digital devices challenge the nature of ownership](https://www.economist.com/news/leaders/21729745-and-threaten-property-rights-digital-age-how-digital-devices-challenge-nature)

在數位時代裡，企業及工廠創造出更多便利生活的數位機械，但是消費者購買產品後，只能淪為使用者，而非支配者、擁有者？

在數位環境中，著作之非法重製與散布變得輕而易舉。美國早在1998 年頒布數位千禧年著作權法（Digital Millennium Copyright Act, DMCA），此反規避條款之制定可讓著作權人在法律的幫助下，自行設置科技保護措施，以維護數位著作權不受侵害。卻也被著作權人用來擴張其著作權，進而達到限制競爭的目的。最簡單的例子就是：使用IPhone，若Home鍵壞了，幾乎沒辦法找人維修，只能送回原廠換新。其他的例子包括汽車、農具機械、洗衣機、甚至是情趣用品等等任何你想的到的數位化產品都在其中。

但這些產品製造商有很多好理由保護其政策，比如：一、確保機器不會發生故障；二、維護環境標準；三、防止駭客入侵。

我們不只面臨所有權不完整的問題，甚至可能遭到隱私權被侵害的風險。比如：iRobot是一台機器人吸塵器，可以清潔地板，也可以創建家庭內部的數位地圖，然後將其出售給廣告商（儘管製造商表示無意這樣做）。

生產者所供應的產品性質正在改變，產品銷售是基於他們授權人們做他們想做的事情。我們更應該思考如何界定生產者之著作權和消費者之所有權的標準，取得適當拿捏。

# [Where might the next crisis come from?](https://www.economist.com/blogs/buttonwood/2017/08/ten-years)

2008年．信貸緊縮的政策和對銀行體系信心的喪失導致了雷曼兄弟的破產，緊接著到來了更加強烈的金融風暴。十年之後的今天，總債務上升，達到了217trn和327%GDP。但與十年前不同的是，這些債務更多的是由政府欠下，由中央銀行持有的。銀行持有更多資本能夠更加保證安全，低利率也更能讓消費者和廠商滿意。現在美聯儲正在謹慎處理更加緊縮的利率，但歐、日、英的中央銀行還沒有做出舉動。

危機的出現可能會有以下原因。一是違約率的急劇上升。二是利率的顯著提高。朝鮮爆發戰爭的可能性和中國地方政府債務的問題也許會使經濟陷入困境。公司債券市場流動性的下降可能引發持有者的恐慌性拋售，造成利率的上升。

危機還有可能因貨幣政策的失誤而出現，美國的定量寬鬆和緊縮的政策在它佔有GDP重大權重的現實背景下會對整個世界產生漣漪效應，從而傳播危機到整個世界。

# [Uber runs into a wall in London ](https://www.economist.com/news/britain/21729768-transport-london-accuses-app-not-reporting-serious-crimes-or-conducting-safety-checks)
從2012年開始，Uber開始在英國合法經營。但9月下旬，倫敦交通局決定不再更新Uber司機的執照。

英國倫敦交通局列舉了幾個禁止Uber的原因：

1.重大犯罪案件回報不實：倫敦警方曾向交通局反應，這一年來Uber司機和乘客多次發生性侵和暴力事件，但Uber並未向警方通報。

2.司機的醫療證明之取得不合乎規定。

3.倫敦交通局不滿意Uber對於在倫敦地區使用Greyball軟體之解釋。

倫敦人也對這項禁令感到吃驚，因為倫敦是Uber在歐洲僅次於巴黎的第二大市場。在倫敦有將近4萬名Uber司機，350萬名使用者（佔全球使用者5％）。

Uber的新老闆承認他們確實有疏失，也有在改進，認為倫敦交通局太大驚小怪了，並起表示他們將對這個禁令進行上訴。倘若上訴失敗了，Uber還是能透過在倫敦以外的地區註冊司機繼續營運。對於目前的禁令，Uber已經收集到超過80萬人連署簽名的請願書。但結果如何尚未可知，上訴期可能會長達一年甚至超過。

註：

Uber之興起：2012年倫敦舉辦夏季奧運前，Uber取得了倫敦交通局核發的營業執照。當時的英國正從經濟衰退中逐漸復甦，Uber的出現創造了不少的就業機會。
2.爭議來源： Uber取得的執照是私人出租車（private hire vehicle）執照，而非計程車（taxi）執照、Uber司機的門檻太低。

# [Taxing fat and subsidising healthy eating widens inequality](https://www.economist.com/news/finance-and-economics/21730033-study-suggests-lower-income-families-end-up-paying-more-their-food-taxing-fat)
在許多先進國家中，人民的肥胖問題越趨嚴重，自從匈牙利於2011年對高熱量食物及糖分課稅後，許多國家也效法跟上。

但窮人於食物上花費的比例更高且更傾向於吃垃圾食物，法國有研究指出，月收入在€1,500以下的成年人有超過20%的肥胖比例；相較於月收入在€3,000以上的成年人，卻只有不到10%的肥胖比例。
但政府要如何課徵肥胖稅，目前主要有兩種方式:

第一種就是對"胖子"課稅，換句話說就是對所謂垃圾食物課稅，但根據上述統計，這種課稅方式相對提高窮人負擔，在政策上相對殘忍。

第二種方式就是對"瘦子"補助，也就是補助那些健康食品如蔬菜水果，但有研究指出富人更傾向於購買健康食品。雖說第二種方式有助於各收入群提升購買健康食物的意願，但富人卻是較大的受惠者。
無論是哪種方法都會相對拉大貧富不公，因此以長期來講最好的策略還是明確的"教育"。

此篇並未提到有關於各國的課徵肥胖稅成效及解決方案，因此我查了幾篇相關報導。
[丹麥於2011年徵收肥胖稅，2012年取消，由於人民大量向外國購入以避稅。](http://intl.ce.cn/specials/zxxx/201211/12/t20121112_23839483.shtml)。

[匈牙利首先課徵肥胖稅，零食物價上漲，減少肥胖且降低嚴重財政赤字。](https://nutri.jtf.org.tw/index.php?idd=1&aid=51&bid=733&cid=1574
)
[英國明年開徵糖稅，擺脫西歐最胖。](https://theinitium.com/article/20160319-dailynews-uk-sugar-tax/)

# [The air around North Korea is getting crowded](https://www.economist.com/news/asia/21730005-least-ten-foreign-radio-stations-are-aiming-their-broadcasts-nuclear-dictatorship-air)
一直以來北韓境內合法的廣播內容不外乎，領土主權的宣揚、真實性有待商確的農產產量成果報告，或是核子物理研究所的最新發明成果。可以違法接收短波無線電的收音機，則至少能接收到10個以上來自他國發射台的訊號，當然也包括韓國。

波無線電乘載的內容從煽動人士激進的言論、K-pop音樂，到由英國BBC提供的時事新聞、天氣預報及英文教學。而Voice of America的調查也顯示，有29%的脫北者曾收聽過這些違法的外國電台；而曾接受過外國資訊的比例絕對是大於該數據，即使在毫無言論自由的北韓，口耳相傳的力量仍不可忽視。

多數北韓人民會以賄賂方式收買巡邏隊員，北韓當局為更徹底地防止人民接收外國資訊，當局也曾嘗試在相近頻率上播放北韓歌曲以阻絕外國資訊，而BBC則對此相當不以為然，認為訊號不可能這麼容易被干擾。
