---
output:
  html_document: default
---
# 2017-10-25 {-}

# [How to judge whether deregulation is going too far](https://www.economist.com/news/leaders/21730148-donald-trumps-regulatory-policy-strange-mix-thoughtful-and-dangerous-how-judge-whether)
作者:林詩璇

川普上任後，新條例的流動便有漸漸減少趨勢。此外，川普幕僚更聲稱，將再也不會像過去一樣，使用條例取代立法，且對於新政策的效果嚴厲評估，已能夠減少對於經濟上所帶來的負擔。對於如此作法，提出其中兩項目標。第ㄧ，對於行政上的過度管制，過去歐巴馬時代，許多政策便受到國會抵制，造成許多法條實施上的停滯，最具代表性例子即是CPP(潔淨電力法案- 溫室氣體減排行動），便受到EPA（美國國家環境保護局）所提出的相當疑問而受阻礙，諸如此類事件，造成過去歐巴馬政府任期時，所推動的許多環保條例（像是有關水道的法規措施）無法完整實施成效;第二，主要針對法條成效上的嚴格分析，過去對於政府介入的理念過度樂觀，導致違反經濟邏輯的謬誤（像是提高加班勞工的工資～造成市場均衡失調現象)，這些對於現任川普政府而言，都是積極要去挑戰，改善過去受官府體制規範下，難以行使的權利及法條，然而，承諾將不再重蹈覆徹的川普，在擁有專業幕僚協助下，的確較少過去餘力不足情形發生，但就現實而言，真正令川普的立法機關擔心是，對於政府機關在減少其管治成本下，卻忽略其中可能伴隨帶給消費者或市民的潛在利益，像是有可能對環境造成浩劫的法規條例，所隱含的高成本，另一方面也富含高效益的經濟價值。
對於管理者而言，極大化社會利潤是一項崇高目標，不是只要取悅公司、企業，取而代之的是，明確定義及修正市場失靈，提升整體競爭力。

因此，文章最後所提出川普的條例措施規範對於”反托拉斯政策“的相關見解：過去，由於政府管理機構過於寬鬆管制下，使得許多企業增加市場力，如今，川普若繼續加強執行反托拉斯，而忽略老闆們的抱怨，表示他的行政幕僚單位是經深思後所執行的;反之，將只是想以經濟之名而掌控的新企圖。
根據上述所說,台灣也是如此,一政策效果執行的背後,無似乎關連到的便是執行成本以及效果代價,兩者之間如何拿捏與運用,是政府部門必須嚴格審查監督的, 尤以環保議題更為爭議,,台灣近代環保議題-核能發電廠紛爭聲波,便是明顯例子,猶如標題”成本效益分析”,企業上常使用的追求利潤方法,當今,用來衡量政府政策上的有效工具,適合不過!


# [Higher taxes can lower inequality without denting economic growth](https://www.economist.com/news/finance-and-economics/21730423-new-study-imf-finds-no-strong-correlation-between-lower-taxes-and-higher)
作者:蘇怡叡

全球經濟不斷進步，21世紀的社會中，人們越來越注重「平等」。為了使社會更加平等，政府實行財政政策，其中最熟知的便是向人民課稅，促進所得重分配。但是，經濟學人發現近年來西方國家從高所得族群收到的稅收越來越少。造成此結果的可能原因經濟學人推測：

1.全球化使得高所得族群繳稅變得「有彈性」。可以自由地移轉財產到世界各地，因此高所得族群會選擇在低稅率的國家繳稅，就算母國實施高稅率，也課不到稅。

2.高所得族群的平均薪資降低，因此整體稅收也減少。但是全球的貧富差距越來越大，很顯然，這不是正確的推論。

3.社會形成降低高所得族群稅率的共識。很顯然，這也不是正確的推論。

4.政府為了增加投資的誘因，因此降低稅率，刺激經濟成長。這是經濟學理論告訴我們的：當利率降低，借貸成本變低，人們會更有投資的意願，更多的投資會使GDP成長。但是IMF卻指出，1981-2016間OECD各國的課稅政策和經濟成長率之間並無明顯相關。若想要促進國內的所得重分配，更應當提高對高所得族群的稅率，而提高稅率並不會為經濟成長造成嚴重衝擊。

雖然研究報告如此，但是各國政府還是傾向以低稅率吸引企業留下並繳稅。想要以稅率改善不公平，IMF提出改變課稅的「對象」。有鑑於資金的高流動性較難課稅，若以流動性較低的不動產為對象課稅或許比較能課到稅。

儘管IMF提出證明「高稅率可改善不平等且不會造成經濟衰退」，目前各國卻依然沉浸在「低利率，高投資」的迷思中。


# [Workers are not switching jobs more ofte](https://www.economist.com/news/finance-and-economics/21730440-millennials-it-turns-out-are-loyal-and-boring-previous)
作者:趙羽涵

多數人認為千世代（出生在1982年後的人）對於工作的忠誠度較低、換工作的速度較快，從數據上來看，是的，然而衡量換工作的頻率不應該由「哪個世代出生」來比較，而是該從過去到現在的「相同年齡層」來比較才較有說服力。

根據2016美國的調查資料指出， 25-45歲年紀的人平均每家公司工作年數呈現稍微下滑。而因為低技術性工作的需求及工會數量減少，45-54歲的男子平均每家公司工作年數反而呈現急速驟降（從1983的12.8年變成8.4年）；中年女性則因為退休年齡提高反而有平均工作年數增加的趨勢。然而，不論年紀，美國人回到家鄉找工作的比例呈現明顯下滑趨勢。

另一個換工作頻繁的地區則是西歐，近年來各年齡層除了年輕世代外，平均每家公司工作年數呈現上升趨勢。這可能是因為當地勞動法規所導致，因為據調查其實年輕世代自願更換工作的比例是較上個世代來得低的。

因此，結構性因素可能才是年輕人更換工作頻繁的關鍵所在。


#  [The gender pay gap](https://www.economist.com/news/international/21729993-women-still-earn-lot-less-men-despite-decades-equal-pay-laws-why-gender)
作者:沈宜妮

“我一直想成為一個媽媽，”Meghan說，一個有兩個孩子的英國女人。她也想要職業生涯，在倫敦的一家大型會計師事務所。當她的女兒出生後，面對著她的職業生涯和她想成為的母親之間的選擇，在老闆拒絕了她靈活的工作時間表後，她辭職了。對女性職業的“母親處罰”，是前端國家男女薪酬差距不再縮小的主因。
*困境

高等收入的國家中，全職工作的女性工資中位數是男性的85％。婦女薪資較低、晉昇機會很少超過男子，高管階層大約只有五分之一是女性。
以婦女為主的職業狀況和薪酬較低。美國女老師、護士、秘書和清潔工，至少有80％是女性，而女性在離婚或喪偶後，往往會變得更貧窮，對企業和社會而言都是一個問題。
研究比較了使用刻板男性詞（領導者，競爭力等）或女性話語（例如支持，人際關係和理解）工作的反應。婦女發現“陽剛”的工作較不吸引人，不是因為他們覺得無法做到這一點，而是他們把這些話看作是一個以男性為主的工作場所的信號。雖有大量的方案鼓勵女孩進入科學和工程，婦女獲得的商業和管理學位的比例穩步上升，但在管理和高級工作中的婦女比例並沒有跟上。

*原因

婦女過去不太可能要求晉升，原因是第一次晉升的機會往往與想要開始一個家庭相吻合。英國的數據表明，女性薪資年齡開始落後於男子，通常擁有第一個孩子的年齡相符。一些新媽媽因為喜歡自己成為孩子的主要照顧者而離職，許多國家認為，有一個工作的母親對學齡前兒童是有害的，而且托兒費用高昂，母親也經常去兼職，從事需少教育或經驗的工作。

*改善方法與未來展望

幾十年來提供有薪產假。當它持續一年或更短時間，它提高了婦女的就業。四分之一的婦女在分娩後十天內恢復工作，但許多人永遠不會復工，因為他們不能忍受在育兒中離開新生兒，而長時間的休工使技能生鏽。

如果沒有有薪產假，夫妻通常決定由母親應該承擔這一切，刻板印象認定母親為育兒專家。研究顯示，為五歲以下兒童提供兒童保育和教育，與兒童母親的就業率提高密切相關。將兒童保育價格降低一半，會使母親的工作時數增加了7-10％。但即使明智設計的生育政策，短時間內婦女也不會在工作上趕上男子。

近一半的年輕父親說，他們想轉移到一個彈性較高的工作，平衡工作和家庭，希望獲得父親與工作相結合的建議。這是否意味著男性對於家庭的重視也在日漸提高？


# [ A Lloyd’s report urges insurers to ask “what if?” ](https://www.economist.com/news/finance-and-economics/21730445-counterfactual-risk-analysis-might-improve-underwriting-lloyds-report-urges)
作者:簡士祺

7月7號，加拿大航空僅差五秒，便有可能因撞機造成500多人的死亡，成為史上最大的飛安事故，但這件事情因為沒人傷亡而不被眾人知曉，針對大眾忽視這種差一點就發生的意外，勞合社(Lloyd’s of London)認為這是保險業漏掉的機會。

以往保險業者對保險費用的定價是根據過去發生的意外費用及機率計算，例如墜毀了幾架飛機，和帶來多少損失。然而近幾年因為出事機率較往年低，使他們認為風險下降了，保險費便沒有上漲的空間，這對市場是相當危險的，尤其是當大災難發生時。不像一般車禍或是搶劫，大型事故的發生機率極低，使得以往保險業者的評估方式顯得不足，因為資料數不足，無法準確的估算災難可能發生頻率，及損失大小，這將使得保險業出現一個漏洞。

為了彌補這個空缺，勞合社提出了看法，建立假設損失在差一點發生，或是有可能更糟的情況，並乘上發生的機率，藉以加深保險業者的資料庫，使得人們對大型災難有所警戒。若是將每個差一點發生的損失詳細計算，那樣的成本實在過高，更好的方法是把許多人、企業、政府，一並納入保險對象，使得災難發生時可以有效承擔費用。