---
output:
  html_document: default
---
# 2017.11.29 {-}

# [Dairy farming is polluting New Zealand’s water](https://www.economist.com/news/asia/21731435-government-data-suggests-60-rivers-and-lakes-are-unswimmable-dairy-farming-polluting-new)
作者:陳昱希

在2013年公佈的數據顯示，紐西蘭有60％的水源是受到汙染的，這與我們傳統認知的紐西蘭有極大的差距，而使其惡化很大的原因為乳牛，現在約有660萬隻牛被擠進了僅有470萬人口的紐西蘭，而本篇主要解釋為何乳牛會為他們帶來水質汙染。

首先，氮肥能用於提高飼料產量，但是氮一旦進入水中會造成有毒的藻類生長；另外，牛糞往往會直接流入河流中，而其中會含有大量的大腸桿菌，數據顯示，紐西蘭人比英國人患大腸桿菌可能性高兩倍，比澳洲人或加拿大人高出三倍；此外，過多的牛群造成河流萎縮，一個數據顯示，2000個用量最大的畜牧業人士消耗了大約6000萬人的用水量。

而紐西蘭當地政府也擬定一些應對措施，如通過限額，農民可以進行氮排放交易；National Party則啟動新的計畫，預計在2040年前達到90%安全水質，然而有學者吐槽這計畫只是降低污染標準，使河流看起來更乾淨；而Labour Party選舉中承諾要徵稅，並用稅來清理河流，但人民不喜歡其徵稅的做法，因此也做罷；新總理Jacinda Ardern表示，她將課瓶裝和出口當地水資源公司的稅，但這只不過是做做樣子，因為這只佔用水資源的一小部分。綜合以上，紐西蘭對於水汙染貌似還沒有一個實際的解決方案。


# [Who needs America?](https://www.economist.com/news/finance-and-economics/21731428-eleven-countries-resurrect-trans-pacific-partnership-who-needs-america)
作者:賴芳誼

以美國為首的12個國家所聯合商議的”跨太平洋夥伴協定” (TPP)命運多舛，隨著新上任的美方領導人宣布退出此多邊協議，將近60%的貿易總量瞬間蒸發，使得拯救瀕死的TPP成為幾近不可能的任務。

但事情似乎有了轉機，2017年11月11日，TPP或許將以一個更饒口的名字「跨太平洋夥伴全面進展協定」(CPTPP) 復活。除美國之外的11個國家部長級領導聯合發表了聲明，宣稱其認同CPTPP的核心元素，並指出此協議「堅決承諾開放市場」，政治意味濃厚。

不過到目前為止，CPTPP離完整協定還有一大段距離，沒有了美國這老大哥的市場，過往各國勉強承諾的讓步就不再有意義。包含馬來西亞、汶萊、越南等國都要求更長的寬容期來調整他們的政策。
其中墨西哥跟加拿大帶來更棘手的問題:若他們加入CPTPP的協商，將會影響其與美國在「北美自由貿易協定」(NAFTA)的談判。這也使得原本11月10日看似能完成的協議，隨著加拿大的臨時反悔而有了戲劇性的破局。

不過即使存在某些談判困難，CPTPP整體上仍與原協議十分相似，它保留了TPP中達成一致的市場准入。
而美國的缺席的確減少了協議的經濟收益，但並沒有完全消除利益。否則放棄這項協議將浪費多年的談判，並喪失了升級現有貿易協定、刺激經濟改革的機會。各國預計在2018年第一季訂下CPTPP的協議，即使美國拒絕加入，其他人仍看到此協議的價值。


# [The future of online retailing is bright](https://www.economist.com/news/special-report/21730541-how-e-commerce-will-change-cities-and-jobs-future-online-retailing-bright)
作者:林凊妤

隨著科技進步、網路普及，電子商務早已涵蓋多數人的生活。但電商並不會淘汰所有零售業，那些提供出色的、特別的商品服務的仍會被保留。在美國，電商已約佔零售消費的十分之一；若這個比例上升到五分之一、三分之一時，影響將是更巨大。從長遠來看，電子商務的影響不會局限於傳統的零售業，它也將改變消費者的生活習慣、改變環境、中斷勞工的勞動時間，重塑政府對企業權力的看法。

對消費者來說，電商帶來了黃金時代。消費者可以從比以前更多更好的產品中進行選擇，花費更少的時間和精力來獲得想要的產品。而廠商間的競爭也將因此更佳激烈。
隨著電商發展，有關隱私權的爭論，也隨之加劇。電子隱私信息中心負責人Marc Rotenberg表示，電商公司聲稱他們使用匿名，但他們的方法是不透明的。而且事實上，企業只是告訴消費者“我們會照顧它”。

目前為止，電商對地理景觀有顯著變化的多是在經濟強國，特別是美國。比如最近Macy's，Gap和American Eagle等品牌實體店面關閉的消息。隨著對實體店舖的需求下降，對於倉儲的需求將上升。花旗估計，未來20年全球將需要23億平方英尺的倉儲空間，相當於大約20000個足球場。未來公司會希望在靠近消費者中心的地方建立倉庫及物流中心，例如，在倫敦北部的恩菲爾德（Enfield），物流中心和新房子是建造在一起的。（原先：住商分離）

就業方面，目前為止美國傳統零售業的下滑似乎與倉儲業務的上升抵消。根據機構進步政策研究所的邁克爾·曼德爾Michael Mandel所說，“在2007年至2017年間，零售工作的數量減少了14萬，電子商務和倉儲則增長了約40萬。但是工作的淨收益可能只是暫時的。商店才剛開始關閉，僅剩的也只是還在測試自動化，且在未來更多的機器人也將在倉庫中使用。這不是一件壞事，在美國真正的零售工資已經持平三十年。技術變革將提高生產力，創造新的工作類型，留下的工作可能會更好。

亞馬遜和阿里巴巴是一個從網絡效應中受益的新一代企業集團。當越來越多的消費者聚集在一起時，越多的賣家會湧向他們，進而吸引更多的消費者。這並不意味著他們將主導每一個行業或市場，但他們的存在卻可以重塑該行業。問題不在於他們是否將拖垮零售業，製造業和物流業，而是接下來哪些行業或社會將被他們所改變。

補充：電子商務（Electronic Commerce, E-Commerce），指的是透過電子化技術（通常是網路）來進行交易、訊息傳遞的商業模式。 電子商務已可應用於B2B、B2C、C2C、C2B 的經營型態。 這種利用網路進行零售生意（Retail）的企業行號，也被稱為E-tailer


# [Why the Federal Reserve should keep its balance-sheet large](https://www.economist.com/news/finance-and-economics/21720601-abundance-money-enhances-economic-efficiency-and-financial-stability-why)
作者:梁雅婷

市面上應該存在多少錢?聯準會最近身陷於這個艱難的問題。自2008金融海嘯以來，美國資產負債表膨脹了5倍，而在今年10月宣布實施縮表政策。

2008金融海嘯後，為了促使景氣復甦實施了三次QE政策，使利率大幅降低，為了拿回對利率的掌控權，聯準會開始付利息給超額準備金，也就是說聯準會可以任意改變貨幣數量的多寡而無須擔心此舉對利率的影響。

1969 Friedman指出持有貨幣是有成本的，因為持有貨幣表示必須放棄將之拿去投資所賺到的利息，除非持有貨幣也能獲得利息，這也就是聯準會做的事情 - 利息給超額準備金。然而此舉是有風險的，當貨幣需求增加但數量不夠時，私部門開始發行短期的貨幣類型債券像是 commercial paper，使熱錢湧入形成泡沫，這也是2008年晚期經融市場崩盤的主要原因之一。

因此，增加貨幣數量可使經濟趨於穩定，美國因而實施QE政策，而今美國想藉由縮表使利率回升，但此舉也必須減少市面上的貨幣數量，是否有其他方法能使長期利率回升呢?答案是有的。聯準會可將長期債券轉為短期債券，轉換之前的扭曲操作政策。
文章到了這邊作者提出了一個瘋狂的想法：為何不讓個人及公司能在聯準會開戶頭呢?如此一來可以膨脹聯準會的資產負債表，又可以減少因政府介入而導致的無效率。這個想法類似於"狹義銀行"，也就是消費者的儲蓄是由政府公債作為擔保，而非無流動性的長期貸款。反對者認為此舉剝奪銀行提供的低率貸款會使市場上貸款人減少，支持者則回應聯準會可隨時降低利率或買入資產。

 如此複雜的金融轉換尚未結束，即便美國實施縮表政策，美國的資產負債表仍會比金融海嘯前大。


# [Sustainable investment joins the mainstream](https://www.economist.com/news/finance-and-economics/21731640-millennials-are-coming-money-and-want-invest-it-responsibly-sustainable)
作者:蔡安琦

SRI(Socially Responsible Investment)--社會責任投資，是指在傳統財務指標之外，同時考量人權議題、環境保育、社會貢獻等倫理價值的投資模式。不同於傳統投資講究經濟層面的可看性，社會責任投資將社會關懷和環境永續納入投資決策的評估要素，目的就是要創造長期穩定的正向價值。

Y世代的青年人正試圖把SRI推高成主流，聲音大到連華爾街也聽到了--高盛投資的資產項目就有100億屬於ESG(ie, meeting environmental, social and governance criteria)。

在大學的成效更是顯而易見，商學院開設有關SRI、ESG的課程，選修人數都已超過上限名額。
德高望重的名人也是促進SRI發展幕後推手之一，比如"Giving Pledge"，由比爾蓋茲等人共建的基金平台，已經有125人連署站出來力挺。

引領潮流的Y世代族群，秉著對永續發展的信念，正慢慢改變世界的價值觀。或許有些人說這群80，90年代的人的所得很低，甚至還比上一輩的父母還低；但事實是，2020年代，他們將繼承遺產，成為這個世界的主人翁，並以行動和實權改變我們所處的社會。

拜現代科技所賜，計算指標性的社會貢獻程度更加容易，企業不再只是資產負債透明，社會價值的評估也走向清晰，也幫助SRI的進程更加明朗化。


# [A hated tax but a fair one](https://www.economist.com/news/leaders/21731626-case-taxing-inherited-assets-strong-hated-tax-fair-one)
作者:徐冰

遺產稅長期以來被認為是不公平的，並且在這方面窮人的反對甚至比富人更加強烈。與60年代相比，美國的遺產稅稅率已經下降了95%，眾議院的稅收改革計畫表明在2025年前將徹底廢除“死亡稅”。經合組織成員國的稅收收入占政府總收入的比例也已經大幅下降，但這樣的低稅收應該不會持久。面對遺產稅的徵收有兩種不同的自由主義原則：一是政府應該讓人們自由處置財富；另一種是財富的繼承會導致社會的不公平。

有些人認為應當徵收懲罰性遺產稅，這種觀點認為死者是沒有權利支配財富的。作者認為這種觀點是不對的，財富是私人擁有的，留給子女可以為他們提供幫助，剝奪了這種權利將會是殘忍的。

認為應當徵收遺產稅的人認為它促進了公平與平等。然而由於近來對遺產稅稅率的降低，富翁的繼承者們更多地繼承了他們的財富。但這種世襲的富人階層也不只源自繼承，同階層的人之間的婚姻也是原因之一。

另一個極端認為根本不應該徵收遺產稅，這些人認為遺產是已經徵稅之後的勞動成果。遺產稅的徵收可能會迫使繼承人出售繼承下來的產業，而這樣就會出現雙重徵稅的現象。但繼承人減價賣掉產業的風險可以由分期支付遺產稅的方式來解決。

相比於其他稅種來說，人們對遺產稅的敵意應該更少。遺產稅不會像所得稅一樣破壞工作的動力（繼承更多財富的人會有更大可能離開工作崗位），房地產稅也不能阻止儲蓄或投資。用遺產稅的稅收收入替代其他稅收可以有更高的效率。

徵收遺產稅有三種設計原則：

首先，對於富人來說，徵收繼承稅而不是房產稅，並且設置一個免稅閾值；

其次，通過設定固定利率和終身津貼的方式填補逃稅漏洞,將利率設定得足夠高以募集大量資金，但又不能高到讓大家逃避稅收的程度；

第三，提高遺產稅的財政收入，減少其他稅收，從而減輕大多數人的負擔。


# [In Japan, the move from cash to plastic goes slowly](https://www.economist.com/news/finance-and-economics/21730925-fragmented-market-imposes-costs-retailers-and-consumers-alike-japan)
作者:黃智彙

日本有些商店以多種方式接受付款，例如信用卡、借記卡、預付卡、手機錢包、apple pay 、支付寶，甚至還有比特幣。但現金支付仍是主流，去年佔消費份額的62%（美國34%、英國22%、韓國10%、中國50%）。

日本目前致力於去現金化，因為處理紙幣與硬幣對企業來說成本相對昂貴。而持續的通膨不足阻礙了價格上漲，許多企業的利潤率因此很低。政府認為無現金支付能刺激經濟、鼓勵消費，同時增加稅收。企業家認為，無現金支付的方式，其消費數據也許能促進新的業務。

許多大型零售商推出自己的卡片，如樂天，但通常這種卡片無法在各個管道使用，客戶可能會覺得便利性不足，商家也會覺得自己多了安裝多個設備的成本。並且，許多企業仍拒絕接受信用卡，這將流失許多遊客的消費，例如麥當勞可以用13種不同的預付卡，卻不能用visa或MasterCard 。

隨著日本去現金化的趨勢，支付市場的分化可能會越來越糟，如果政府想達到十年內現金使用減半的目標，可能需要進行管制以遏止現金之使用。